# fly.toml app configuration file generated for strava-peaks-api on 2025-07-15T11:23:05-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# fly.toml (root of the repo)

app = "strava-peaks-api"
primary_region = "iad"

[env]
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 40

  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    method = "GET"
    path = "/health"

